version: 2.1

jobs:
  test:
    docker:
      - image: python:3.9  # Use the appropriate Python version for your project
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Make migrations
          command: python manage.py makemigrations
          
      - run:
          name: Set up test database
          command: python manage.py migrate

      - run:
          name: Run tests
          command: python manage.py test api.tests

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
