# Generated by Django 4.2.2 on 2023-06-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikeDislike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=200)),
                ("postId", models.IntegerField()),
                ("like", models.BooleanField(default=False)),
                ("dislike", models.BooleanField(default=False)),
            ],
        ),
    ]
